export const testimonials = [
    {
      id: 1,
      rating: 5,
      text: "Good Food And Good Service. I Really Loved It 😍",
      name: "Aman Yadav",
      date: "2024-06-24",
      timeAgo: "6 Months Ago",
      avatar: "A",
    },
    {
      id: 2,
      rating: 4,
      text: "One Of the best website for food delivery. I Really Loved It 😍",
      name: "Ritik Singh Chauhan",
      date: "2024-05-30",
      timeAgo: "6 Months Ago",
      avatar: "R",
    },
    {
      id: 3,
      rating: 4.5,
      text: "I Really Loved It 😍",
      name: "Prince Napali",
      date: "2024-05-11",
      timeAgo: "7 Months Ago",
      avatar: "https://randomuser.me/api/portraits/men/1.jpg", 
    },
    {
      id: 4,
      rating: 2,
      text: "provide fast delivery .",
      name: "Gaurav Kumar",
      date: "2024-03-30",
      timeAgo: "8 Months Ago",
      avatar: "GK",
    },
    {
      id: 5,
      rating: 3,
      text: "Food Is Delicious But Delivery Boy Attitude Very Bad",
      name: "Sandeep kamboz",
      date: "2024-03-22",
      timeAgo: "9 Months Ago",
      avatar: "SK",
    },
    {
      id: 6,
      rating: 5,
      text: "The Food Was Delicious. The Delivery Was On Time.",
      name: "Rinkal Arora❤",
      date: "2024-03-07",
      timeAgo: "9 Months Ago",
      avatar: "RA❤",
    },
    {
      id: 7,
      rating: 5,
      text: "Best offers deals and discount all the time.",
      name: "Dikhsha 🎉",
      date: "2024-03-01",
      timeAgo: "9 Months Ago",
      avatar: "D",
    },
    {
      id: 8,
      rating: 5,
      text: "All the food items are available at reasonable price.",
      name: "Masoom Sharma",
      date: "2024-02-28",
      timeAgo: "9 Months Ago",
      avatar: "https://randomuser.me/api/portraits/women/2.jpg",
    },
  ];
  